// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoDto.proto

package Dto;

public final class ProtoDto {
  private ProtoDto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DtoExampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Dto.DtoExample)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated uint32 numbers = 3;</code>
     */
    java.util.List<java.lang.Integer> getNumbersList();
    /**
     * <code>repeated uint32 numbers = 3;</code>
     */
    int getNumbersCount();
    /**
     * <code>repeated uint32 numbers = 3;</code>
     */
    int getNumbers(int index);

    /**
     * <code>.Dto.InnerDto inner_dto = 4;</code>
     */
    boolean hasInnerDto();
    /**
     * <code>.Dto.InnerDto inner_dto = 4;</code>
     */
    Dto.ProtoDto.InnerDto getInnerDto();
    /**
     * <code>.Dto.InnerDto inner_dto = 4;</code>
     */
    Dto.ProtoDto.InnerDtoOrBuilder getInnerDtoOrBuilder();
  }
  /**
   * Protobuf type {@code Dto.DtoExample}
   */
  public  static final class DtoExample extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Dto.DtoExample)
      DtoExampleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DtoExample.newBuilder() to construct.
    private DtoExample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DtoExample() {
      name_ = "";
      numbers_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DtoExample();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DtoExample(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                numbers_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              numbers_.addInt(input.readUInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                numbers_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                numbers_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              Dto.ProtoDto.InnerDto.Builder subBuilder = null;
              if (innerDto_ != null) {
                subBuilder = innerDto_.toBuilder();
              }
              innerDto_ = input.readMessage(Dto.ProtoDto.InnerDto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(innerDto_);
                innerDto_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          numbers_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Dto.ProtoDto.internal_static_Dto_DtoExample_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Dto.ProtoDto.internal_static_Dto_DtoExample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Dto.ProtoDto.DtoExample.class, Dto.ProtoDto.DtoExample.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBERS_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.IntList numbers_;
    /**
     * <code>repeated uint32 numbers = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getNumbersList() {
      return numbers_;
    }
    /**
     * <code>repeated uint32 numbers = 3;</code>
     */
    public int getNumbersCount() {
      return numbers_.size();
    }
    /**
     * <code>repeated uint32 numbers = 3;</code>
     */
    public int getNumbers(int index) {
      return numbers_.getInt(index);
    }
    private int numbersMemoizedSerializedSize = -1;

    public static final int INNER_DTO_FIELD_NUMBER = 4;
    private Dto.ProtoDto.InnerDto innerDto_;
    /**
     * <code>.Dto.InnerDto inner_dto = 4;</code>
     */
    public boolean hasInnerDto() {
      return innerDto_ != null;
    }
    /**
     * <code>.Dto.InnerDto inner_dto = 4;</code>
     */
    public Dto.ProtoDto.InnerDto getInnerDto() {
      return innerDto_ == null ? Dto.ProtoDto.InnerDto.getDefaultInstance() : innerDto_;
    }
    /**
     * <code>.Dto.InnerDto inner_dto = 4;</code>
     */
    public Dto.ProtoDto.InnerDtoOrBuilder getInnerDtoOrBuilder() {
      return getInnerDto();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (getNumbersList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(numbersMemoizedSerializedSize);
      }
      for (int i = 0; i < numbers_.size(); i++) {
        output.writeUInt32NoTag(numbers_.getInt(i));
      }
      if (innerDto_ != null) {
        output.writeMessage(4, getInnerDto());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < numbers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(numbers_.getInt(i));
        }
        size += dataSize;
        if (!getNumbersList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        numbersMemoizedSerializedSize = dataSize;
      }
      if (innerDto_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getInnerDto());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Dto.ProtoDto.DtoExample)) {
        return super.equals(obj);
      }
      Dto.ProtoDto.DtoExample other = (Dto.ProtoDto.DtoExample) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getNumbersList()
          .equals(other.getNumbersList())) return false;
      if (hasInnerDto() != other.hasInnerDto()) return false;
      if (hasInnerDto()) {
        if (!getInnerDto()
            .equals(other.getInnerDto())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getNumbersCount() > 0) {
        hash = (37 * hash) + NUMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getNumbersList().hashCode();
      }
      if (hasInnerDto()) {
        hash = (37 * hash) + INNER_DTO_FIELD_NUMBER;
        hash = (53 * hash) + getInnerDto().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Dto.ProtoDto.DtoExample parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dto.ProtoDto.DtoExample parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dto.ProtoDto.DtoExample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dto.ProtoDto.DtoExample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dto.ProtoDto.DtoExample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dto.ProtoDto.DtoExample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dto.ProtoDto.DtoExample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Dto.ProtoDto.DtoExample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Dto.ProtoDto.DtoExample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Dto.ProtoDto.DtoExample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Dto.ProtoDto.DtoExample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Dto.ProtoDto.DtoExample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Dto.ProtoDto.DtoExample prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Dto.DtoExample}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Dto.DtoExample)
        Dto.ProtoDto.DtoExampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Dto.ProtoDto.internal_static_Dto_DtoExample_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Dto.ProtoDto.internal_static_Dto_DtoExample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Dto.ProtoDto.DtoExample.class, Dto.ProtoDto.DtoExample.Builder.class);
      }

      // Construct using Dto.ProtoDto.DtoExample.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        numbers_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        if (innerDtoBuilder_ == null) {
          innerDto_ = null;
        } else {
          innerDto_ = null;
          innerDtoBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Dto.ProtoDto.internal_static_Dto_DtoExample_descriptor;
      }

      @java.lang.Override
      public Dto.ProtoDto.DtoExample getDefaultInstanceForType() {
        return Dto.ProtoDto.DtoExample.getDefaultInstance();
      }

      @java.lang.Override
      public Dto.ProtoDto.DtoExample build() {
        Dto.ProtoDto.DtoExample result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Dto.ProtoDto.DtoExample buildPartial() {
        Dto.ProtoDto.DtoExample result = new Dto.ProtoDto.DtoExample(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        if (((bitField0_ & 0x00000001) != 0)) {
          numbers_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.numbers_ = numbers_;
        if (innerDtoBuilder_ == null) {
          result.innerDto_ = innerDto_;
        } else {
          result.innerDto_ = innerDtoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Dto.ProtoDto.DtoExample) {
          return mergeFrom((Dto.ProtoDto.DtoExample)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Dto.ProtoDto.DtoExample other) {
        if (other == Dto.ProtoDto.DtoExample.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.numbers_.isEmpty()) {
          if (numbers_.isEmpty()) {
            numbers_ = other.numbers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNumbersIsMutable();
            numbers_.addAll(other.numbers_);
          }
          onChanged();
        }
        if (other.hasInnerDto()) {
          mergeInnerDto(other.getInnerDto());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Dto.ProtoDto.DtoExample parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Dto.ProtoDto.DtoExample) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList numbers_ = emptyIntList();
      private void ensureNumbersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          numbers_ = mutableCopy(numbers_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint32 numbers = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getNumbersList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(numbers_) : numbers_;
      }
      /**
       * <code>repeated uint32 numbers = 3;</code>
       */
      public int getNumbersCount() {
        return numbers_.size();
      }
      /**
       * <code>repeated uint32 numbers = 3;</code>
       */
      public int getNumbers(int index) {
        return numbers_.getInt(index);
      }
      /**
       * <code>repeated uint32 numbers = 3;</code>
       */
      public Builder setNumbers(
          int index, int value) {
        ensureNumbersIsMutable();
        numbers_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 numbers = 3;</code>
       */
      public Builder addNumbers(int value) {
        ensureNumbersIsMutable();
        numbers_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 numbers = 3;</code>
       */
      public Builder addAllNumbers(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureNumbersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, numbers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 numbers = 3;</code>
       */
      public Builder clearNumbers() {
        numbers_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private Dto.ProtoDto.InnerDto innerDto_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Dto.ProtoDto.InnerDto, Dto.ProtoDto.InnerDto.Builder, Dto.ProtoDto.InnerDtoOrBuilder> innerDtoBuilder_;
      /**
       * <code>.Dto.InnerDto inner_dto = 4;</code>
       */
      public boolean hasInnerDto() {
        return innerDtoBuilder_ != null || innerDto_ != null;
      }
      /**
       * <code>.Dto.InnerDto inner_dto = 4;</code>
       */
      public Dto.ProtoDto.InnerDto getInnerDto() {
        if (innerDtoBuilder_ == null) {
          return innerDto_ == null ? Dto.ProtoDto.InnerDto.getDefaultInstance() : innerDto_;
        } else {
          return innerDtoBuilder_.getMessage();
        }
      }
      /**
       * <code>.Dto.InnerDto inner_dto = 4;</code>
       */
      public Builder setInnerDto(Dto.ProtoDto.InnerDto value) {
        if (innerDtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          innerDto_ = value;
          onChanged();
        } else {
          innerDtoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Dto.InnerDto inner_dto = 4;</code>
       */
      public Builder setInnerDto(
          Dto.ProtoDto.InnerDto.Builder builderForValue) {
        if (innerDtoBuilder_ == null) {
          innerDto_ = builderForValue.build();
          onChanged();
        } else {
          innerDtoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Dto.InnerDto inner_dto = 4;</code>
       */
      public Builder mergeInnerDto(Dto.ProtoDto.InnerDto value) {
        if (innerDtoBuilder_ == null) {
          if (innerDto_ != null) {
            innerDto_ =
              Dto.ProtoDto.InnerDto.newBuilder(innerDto_).mergeFrom(value).buildPartial();
          } else {
            innerDto_ = value;
          }
          onChanged();
        } else {
          innerDtoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Dto.InnerDto inner_dto = 4;</code>
       */
      public Builder clearInnerDto() {
        if (innerDtoBuilder_ == null) {
          innerDto_ = null;
          onChanged();
        } else {
          innerDto_ = null;
          innerDtoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Dto.InnerDto inner_dto = 4;</code>
       */
      public Dto.ProtoDto.InnerDto.Builder getInnerDtoBuilder() {
        
        onChanged();
        return getInnerDtoFieldBuilder().getBuilder();
      }
      /**
       * <code>.Dto.InnerDto inner_dto = 4;</code>
       */
      public Dto.ProtoDto.InnerDtoOrBuilder getInnerDtoOrBuilder() {
        if (innerDtoBuilder_ != null) {
          return innerDtoBuilder_.getMessageOrBuilder();
        } else {
          return innerDto_ == null ?
              Dto.ProtoDto.InnerDto.getDefaultInstance() : innerDto_;
        }
      }
      /**
       * <code>.Dto.InnerDto inner_dto = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Dto.ProtoDto.InnerDto, Dto.ProtoDto.InnerDto.Builder, Dto.ProtoDto.InnerDtoOrBuilder> 
          getInnerDtoFieldBuilder() {
        if (innerDtoBuilder_ == null) {
          innerDtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Dto.ProtoDto.InnerDto, Dto.ProtoDto.InnerDto.Builder, Dto.ProtoDto.InnerDtoOrBuilder>(
                  getInnerDto(),
                  getParentForChildren(),
                  isClean());
          innerDto_ = null;
        }
        return innerDtoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Dto.DtoExample)
    }

    // @@protoc_insertion_point(class_scope:Dto.DtoExample)
    private static final Dto.ProtoDto.DtoExample DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Dto.ProtoDto.DtoExample();
    }

    public static Dto.ProtoDto.DtoExample getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DtoExample>
        PARSER = new com.google.protobuf.AbstractParser<DtoExample>() {
      @java.lang.Override
      public DtoExample parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DtoExample(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DtoExample> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DtoExample> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Dto.ProtoDto.DtoExample getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InnerDtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Dto.InnerDto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>double x = 2;</code>
     */
    double getX();
  }
  /**
   * Protobuf type {@code Dto.InnerDto}
   */
  public  static final class InnerDto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Dto.InnerDto)
      InnerDtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InnerDto.newBuilder() to construct.
    private InnerDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InnerDto() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InnerDto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InnerDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 17: {

              x_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Dto.ProtoDto.internal_static_Dto_InnerDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Dto.ProtoDto.internal_static_Dto_InnerDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Dto.ProtoDto.InnerDto.class, Dto.ProtoDto.InnerDto.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int X_FIELD_NUMBER = 2;
    private double x_;
    /**
     * <code>double x = 2;</code>
     */
    public double getX() {
      return x_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (x_ != 0D) {
        output.writeDouble(2, x_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (x_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, x_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Dto.ProtoDto.InnerDto)) {
        return super.equals(obj);
      }
      Dto.ProtoDto.InnerDto other = (Dto.ProtoDto.InnerDto) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (java.lang.Double.doubleToLongBits(getX())
          != java.lang.Double.doubleToLongBits(
              other.getX())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getX()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Dto.ProtoDto.InnerDto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dto.ProtoDto.InnerDto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dto.ProtoDto.InnerDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dto.ProtoDto.InnerDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dto.ProtoDto.InnerDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dto.ProtoDto.InnerDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dto.ProtoDto.InnerDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Dto.ProtoDto.InnerDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Dto.ProtoDto.InnerDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Dto.ProtoDto.InnerDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Dto.ProtoDto.InnerDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Dto.ProtoDto.InnerDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Dto.ProtoDto.InnerDto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Dto.InnerDto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Dto.InnerDto)
        Dto.ProtoDto.InnerDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Dto.ProtoDto.internal_static_Dto_InnerDto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Dto.ProtoDto.internal_static_Dto_InnerDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Dto.ProtoDto.InnerDto.class, Dto.ProtoDto.InnerDto.Builder.class);
      }

      // Construct using Dto.ProtoDto.InnerDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        x_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Dto.ProtoDto.internal_static_Dto_InnerDto_descriptor;
      }

      @java.lang.Override
      public Dto.ProtoDto.InnerDto getDefaultInstanceForType() {
        return Dto.ProtoDto.InnerDto.getDefaultInstance();
      }

      @java.lang.Override
      public Dto.ProtoDto.InnerDto build() {
        Dto.ProtoDto.InnerDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Dto.ProtoDto.InnerDto buildPartial() {
        Dto.ProtoDto.InnerDto result = new Dto.ProtoDto.InnerDto(this);
        result.name_ = name_;
        result.x_ = x_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Dto.ProtoDto.InnerDto) {
          return mergeFrom((Dto.ProtoDto.InnerDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Dto.ProtoDto.InnerDto other) {
        if (other == Dto.ProtoDto.InnerDto.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getX() != 0D) {
          setX(other.getX());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Dto.ProtoDto.InnerDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Dto.ProtoDto.InnerDto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private double x_ ;
      /**
       * <code>double x = 2;</code>
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>double x = 2;</code>
       */
      public Builder setX(double value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double x = 2;</code>
       */
      public Builder clearX() {
        
        x_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Dto.InnerDto)
    }

    // @@protoc_insertion_point(class_scope:Dto.InnerDto)
    private static final Dto.ProtoDto.InnerDto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Dto.ProtoDto.InnerDto();
    }

    public static Dto.ProtoDto.InnerDto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InnerDto>
        PARSER = new com.google.protobuf.AbstractParser<InnerDto>() {
      @java.lang.Override
      public InnerDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InnerDto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InnerDto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InnerDto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Dto.ProtoDto.InnerDto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Dto_DtoExample_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Dto_DtoExample_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Dto_InnerDto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Dto_InnerDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ProtoDto.proto\022\003Dto\"Y\n\nDtoExample\022\n\n\002i" +
      "d\030\001 \001(\r\022\014\n\004name\030\002 \001(\t\022\017\n\007numbers\030\003 \003(\r\022 " +
      "\n\tinner_dto\030\004 \001(\0132\r.Dto.InnerDto\"#\n\010Inne" +
      "rDto\022\014\n\004name\030\001 \001(\t\022\t\n\001x\030\002 \001(\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Dto_DtoExample_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Dto_DtoExample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Dto_DtoExample_descriptor,
        new java.lang.String[] { "Id", "Name", "Numbers", "InnerDto", });
    internal_static_Dto_InnerDto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Dto_InnerDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Dto_InnerDto_descriptor,
        new java.lang.String[] { "Name", "X", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
